[project]
name = "bllm"
version = "0.0.1"
description = "Companion for the book - Build a Large Language Model (From Scratch)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.3.2",
    "numpy>=2.2.1",
    "ruff>=0.8.5",
    "tiktoken>=0.8.0",
    "torch>=2.5.1",
]
